#!/usr/bin/env python3
"""
Compare the FLOWR-generated molecules against the known BACE inhibitors, both
docked through the identical DiffDock path.

The load-bearing check here is not the comparison itself but the calibration
that precedes it: on the known set the true affinities are measured, so we can
ask whether DiffDock's pose confidence tracks real activity at all. If it does
not, then no confidence comparison between the two sets can support a claim
about potency, and the honest answer to "are the generated molecules better?"
is that this pipeline cannot say.
"""

import csv
import glob
import math
import os
import re

SELECTISAFE = "/scratch/g.murugan/Pfizer/selectisafe"


def top_conf(base, name):
    """Confidence of the rank-1 pose, read from DiffDock's filename."""
    for p in glob.glob(os.path.join(base, name, "rank1_confidence*.sdf")):
        return float(re.search(r"confidence(-?[\d.]+)\.sdf$", p).group(1))
    return None


def stats(v):
    v = sorted(v)
    n = len(v)
    med = v[n // 2] if n % 2 else (v[n // 2 - 1] + v[n // 2]) / 2
    mean = sum(v) / n
    sd = math.sqrt(sum((x - mean) ** 2 for x in v) / (n - 1))
    return min(v), med, mean, sd, max(v)


def ranks(v):
    """Average ranks, so ties do not distort the correlation."""
    order = sorted(range(len(v)), key=lambda i: v[i])
    out = [0.0] * len(v)
    i = 0
    while i < len(order):
        j = i
        while j + 1 < len(order) and v[order[j + 1]] == v[order[i]]:
            j += 1
        r = (i + j) / 2.0 + 1
        for k in range(i, j + 1):
            out[order[k]] = r
        i = j + 1
    return out


def spearman(x, y):
    rx, ry = ranks(x), ranks(y)
    n = len(x)
    mx, my = sum(rx) / n, sum(ry) / n
    num = sum((rx[i] - mx) * (ry[i] - my) for i in range(n))
    den = math.sqrt(sum((rx[i] - mx) ** 2 for i in range(n))
                    * sum((ry[i] - my) ** 2 for i in range(n)))
    return num / den if den else float("nan")


def mann_whitney(a, b):
    """Two-sided U test, normal approximation -- fine at n=29 vs 36."""
    comb = sorted([(v, 0) for v in a] + [(v, 1) for v in b])
    vals = [v for v, _ in comb]
    rk = ranks(vals)
    r1 = sum(rk[i] for i, (_, g) in enumerate(comb) if g == 0)
    n1, n2 = len(a), len(b)
    u = r1 - n1 * (n1 + 1) / 2.0
    mu = n1 * n2 / 2.0
    sd = math.sqrt(n1 * n2 * (n1 + n2 + 1) / 12.0)
    z = (u - mu) / sd
    return u, z, math.erfc(abs(z) / math.sqrt(2))


def main():
    os.chdir(SELECTISAFE)

    gen = [(r["complex_name"],
            top_conf("data/results/bace_docked_all", r["complex_name"]),
            float(r["pic50"]))
           for r in csv.DictReader(open("data/docking_inputs/manifest.csv"))]
    ref = [(r["source_title"],
            top_conf("data/results/bace_ref_docked", r["complex_name"]),
            float(r["exp_pkd"]))
           for r in csv.DictReader(open("data/docking_inputs/manifest_ref.csv"))]

    for label, rows in (("generated", gen), ("known", ref)):
        missing = [r[0] for r in rows if r[1] is None]
        if missing:
            raise SystemExit("no rank1 pose for %s: %s" % (label, missing))

    gc = [g[1] for g in gen]
    rc = [r[1] for r in ref]

    print("=" * 62)
    print("DOCKING CONFIDENCE  (rank-1 pose, identical DiffDock settings)")
    print("=" * 62)
    print("%-24s %6s %6s %6s %6s %6s" % ("set", "min", "med", "mean", "sd", "max"))
    print("%-24s %6.2f %6.2f %6.2f %6.2f %6.2f" % ("generated (n=29)", *stats(gc)))
    print("%-24s %6.2f %6.2f %6.2f %6.2f %6.2f" % ("known inhibitors (n=36)", *stats(rc)))
    u, z, p = mann_whitney(gc, rc)
    print("\nMann-Whitney U = %.0f   z = %.2f   p = %.4f" % (u, z, p))

    print()
    print("=" * 62)
    print("CALIBRATION: does pose confidence track measured activity?")
    print("=" * 62)
    rho = spearman(rc, [r[2] for r in ref])
    print("Spearman(confidence, experimental pKd) on the known set = %+.3f" % rho)
    print("  n = 36 compounds whose affinity was measured in a lab.")

    print()
    print("=" * 62)
    print("ACTIVITY")
    print("=" * 62)
    gp = [g[2] for g in gen]
    rp = [r[2] for r in ref]
    print("generated  FLOWR pIC50 (PREDICTED): mean %.2f  max %.2f" % (sum(gp) / len(gp), max(gp)))
    print("known      exp pKd     (MEASURED) : mean %.2f  max %.2f" % (sum(rp) / len(rp), max(rp)))

    print()
    print("Top 5 generated by docking confidence:")
    for name, c, pic in sorted(gen, key=lambda r: -r[1])[:5]:
        print("  %-14s conf %5.2f   pIC50(pred) %.2f" % (name, c, pic))
    print("Top 5 known by docking confidence:")
    for name, c, pk in sorted(ref, key=lambda r: -r[1])[:5]:
        print("  %-14s conf %5.2f   pKd(exp)    %.2f" % (name, c, pk))


if __name__ == "__main__":
    main()
